CREATE TABLE Users 
(
    Email VARCHAR(100) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Role VARCHAR(10) NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (Email)
);

CREATE TABLE RefreshTokens
(
    Token VARCHAR(100) NOT NULL,
    CreatedDate DATETIME NOT NULL,
    Expires DATETIME NOT NULL,
    IsEnabled BIT NOT NULL,
    Email VARCHAR(100) NOT NULL,
    CONSTRAINT PK_REFRESHTOKENS PRIMARY KEY (Token),
    CONSTRAINT FK_REFRESHTOKENS_USERS FOREIGN KEY (Email) REFERENCES Users(Email)
);
